name: twitter_auto_post
description: A sample command-line application.
version: 0.0.0 
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev
environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  twitter_client: ^0.0.6
